- provider: kubernetes-pod@v0
  labels: [ elastic, eks ]
  with:
    context: lineville@elastic-machines-multi-cluster.us-west-2.eksctl.io
    namespace: elastic-machines-eks-namespace
    containerImage: ubuntu:focal
    os: linux

- provider: kubernetes-pod@v0
  labels: [ elastic, aks ]
  with:
    context: ci-cd-default-elastic-machines-dev-cluster
    namespace: elastic-machines-aks-namespace
    containerImage: ubuntu:focal
    os: linux

- provider: kubernetes-pod@v0
  labels: [ elastic, eks ]
  with:
    context: lineville@em-integration-testing.us-west-2.eksctl.io
    namespace: default
    containerImage: ubuntu:focal
    os: linux
