- provider: kubernetes-pod@v0
  labels: [ elastic, lineville@elastic-machines-multi-cluster.us-west-2.eksctl.io ]
  with:
    context: lineville@elastic-machines-multi-cluster.us-west-2.eksctl.io
    namespace: elastic-machines-multi-1
    containerImage: ubuntu:focal
    os: linux
  scale:
    - minimumMachines: 1
    - maximumMachines: 2

- provider: kubernetes-pod@v0
  labels: [ elastic, lineville@em-integration-testing.us-west-2.eksctl.io ]
  with:
    context: lineville@em-integration-testing.us-west-2.eksctl.io
    namespace: elastic-machines-multi-2
    containerImage: ubuntu:focal
    os: linux
  scale:
    - minimumMachines: 1
    - maximumMachines: 2

- provider: kubernetes-pod@v0
  labels: [ elastic, ci-cd-default-elastic-machines-dev-cluster ]
  with:
    context: ci-cd-default-elastic-machines-dev-cluster
    namespace: elastic-machines-multi-3
    containerImage: ubuntu:focal
    os: linux
  scale:
    - minimumMachines: 1
    - maximumMachines: 2
