- provider: azure-virtual-machine@v0
  with:
    subscription: 685eed17-13cd-4ade-96cd-28ed2e0c4d53
    resourceGroup: elastic-machines-live
    location: westus3
    image: Canonical:UbuntuServer:18.04-LTS:latest
    vmSku: Standard_DS1_v2
