- provider: kubernetes-pod@v0
  labels: [elastic, elastic-machines-multi-1]
  with:
    namespace: elastic-machines-multi-1
    containerImage: ubuntu:focal
    os: linux
  scale:
    - minimumMachines: 1
    - maximumMachines: 4

- provider: kubernetes-pod@v0
  labels: [elastic, elastic-machines-multi-2]
  with:
    namespace: elastic-machines-multi-2
    containerImage: ubuntu:focal
    os: linux
  scale:
    - minimumMachines: 1
    - maximumMachines: 4